export const actionTypes = {
  GET_ALL_USER_REQUEST: 'GET_ALL_USER_REQUEST',
  GET_ALL_USER_SUCCESS: 'GET_ALL_USER_SUCCESS',
  GET_ALL_USER_FAIL: 'GET_ALL_USER_FAIL',
  GET_USER_INFO: 'GET_USER_INFO',
};
export default actionTypes;